### ISSUE TITLE
kook发送报错

### ISSUE THREAD

**Issue by Nigh** [ACAlexChen/multi-platform-message-forwarding#2]
```
2024-06-01 10:26:36 [E] multi-platform-message-forwarding 消息转发函数错误：TypeError: session.bot.getChannel is not a function
```

KOOK转发至Telegram成功，Telegram转发KOOK报错。

**Comment by Nigh** [comment]
重新配置后未重现。

目前个人测试下列客户端可以正常转发
- onebot
- telegram
- kook
- discord

**Comment by ACAlexChen** [comment]
ok，我知道了，今天会修复这个bug

**Comment by ACAlexChen** [comment]
这个问题也是老生常谈了，在插件2.0.0版本刚出的时候我就测试出了这种问题，主要是适配器没有实现getChannel这个方法，只能通过将所有为实现此方法的适配器单独拉出来从session中获取频道名称
那么为什么不让所有适配器都从session中获取频道名称呢，因为有部分适配器从session中无法获取到频道名称（就很离谱）
当然，你可以通过把ChannelName_Setting选项关闭来解决这个问题

**Comment by Nigh** [comment]
难怪不知道为什么就正常了，原来是因为我关掉显示频道名称了。

**Comment by ACAlexChen** [comment]
已修复，增加一个配置项Which_Platform_Use_getChannel，未在该数组内的平台都会默认从session中获取频道名称
