### ISSUE TITLE
[优化] 优化转发消息格式，增加可读性

### ISSUE THREAD

**Issue by Nigh** [ACAlexChen/multi-platform-message-forwarding#3]
在会自动合并相同用户发言的IM上，如果不加装饰会导致消息混在一起，辨识度比较差。如下图中，只有telegram辨识度尚可。

## Telegram:
![image](https://github.com/ACAlexChen/multi-platform-message-forwarding/assets/1407471/edb93283-159b-460b-846a-50bcf4f05ef8)

## Discord:
![image](https://github.com/ACAlexChen/multi-platform-message-forwarding/assets/1407471/7988ebb9-0526-41b1-a16f-b17c15561bec)

## KOOK:
![image](https://github.com/ACAlexChen/multi-platform-message-forwarding/assets/1407471/27eb1a93-a419-4814-9f71-f094635a3a27)

# 建议

建议如下图，为不同平台编写不同的装饰器，并增加更多的可选装饰字段，比如消息来源平台等。
![image](https://github.com/ACAlexChen/multi-platform-message-forwarding/assets/1407471/246f5cce-bde2-4cc1-b7ce-be0a6654c069)

**Comment by ACAlexChen** [comment]
emmmm，总之就是发送markdown或者html之类的吧，我会考虑你的建议，不过.........我其实不会写markdown和html

**Comment by Nigh** [comment]
其实格式还有不少细节需要处理的。之前有写过一个自用的转发bot，没有时间维护了，所以现在转到koishi上面来了。不过之前做过的一些针对不同平台的格式上的处理还是可以参考下。

- 获取显示用户名
- 合并相同用户连续发言
- reply和at的处理

现在获取的用户名，有一些并不是聊天中显示的昵称，而是用户的ID，这个因为不同平台有不同的逻辑，如果适配器没有相应的接口的话，应该是需要针对不同平台单独处理的。
如果可以编辑消息的话，应当把相同用户的连续发言合并到同一条消息。
reply和at会麻烦一些，需要缓存最近的消息，跨平台at由于肯定是at不到的，所以我之前是转换成了 at昵称 的形式。reply也是需要处理跨平台相关的逻辑，需要转换成reply到当前平台的对应消息。

**Comment by ACAlexChen** [comment]
反正近期我准备对消息转发的底层逻辑大改一下，另外实际上我认为可以通过bind插件和binding表来实现跨平台at，在我另一个插件permission-synchronization中已经用上了这种方法

**Comment by ACAlexChen** [comment]
今天的话增加了kook平台的卡片消息发送支持，其他平台的话最好你帮我去找一下对应平台的开发者文档，我需要参考一下

**Comment by Nigh** [comment]
- Telegram: https://core.telegram.org/bots/api#markdownv2-style
- Discord: https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline

**Comment by LuorixDev** [comment]
tg会以文本显示md
