### ISSUE TITLE
[功能] 增加隐私模式

### ISSUE THREAD

**Issue by Nigh** [ACAlexChen/multi-platform-message-forwarding#6]
提供一个命令能够让当前群组临时退出互联。

国人可能会比较常用。在讨论一些隐私话题时，不希望转发到国内的IM上，需要临时退出这个互联转发组。

**Comment by ACAlexChen** [comment]
已添加，在beta2版本中
TemporaryExclusion <time>（用于临时排除某一群聊，time参数为排除时间，单位为毫秒）
CancelTE（取消排除）

**Comment by ACAlexChen** [comment]
哦对了，这两条指令默认需要权限等级4
